# Generated by Django 4.0 on 2023-09-03 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupStep',
            fields=[
            ],
            options={
                'verbose_name': '测试准备步骤',
                'verbose_name_plural': '测试准备步骤',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.step',),
        ),
        migrations.CreateModel(
            name='TeardownStep',
            fields=[
            ],
            options={
                'verbose_name': '测试清理步骤',
                'verbose_name_plural': '测试清理步骤',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.step',),
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
            ],
            options={
                'verbose_name': '测试步骤',
                'verbose_name_plural': '测试步骤',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.step',),
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': '操作库', 'verbose_name_plural': '操作库'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': '操作方法', 'verbose_name_plural': '操作方法'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': '用例模块', 'verbose_name_plural': '用例模块'},
        ),
        migrations.AlterModelOptions(
            name='testreport',
            options={'verbose_name': '测试报告', 'verbose_name_plural': '测试报告'},
        ),
        migrations.AddField(
            model_name='module',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='app.module', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='module',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='auth.user', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='last_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待运行'), (1, '通过'), (2, '失败'), (3, '异常')], default=0, null=True, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.module', verbose_name='用例模块'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2')], default=1, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to='auth.user', verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='auth.user', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to='auth.user', verbose_name='修改人'),
        ),
    ]
