# Generated by Django 4.0 on 2023-09-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_setupstep_teardownstep_teststep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='description',
        ),
    ]
