# Generated by Django 4.0 on 2023-09-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_step_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='tn_ancestors_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_ancestors_pks',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_children_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_children_pks',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_depth',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_descendants_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_descendants_pks',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_index',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_level',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_parent',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_priority',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_siblings_count',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tn_siblings_pks',
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_modules', to='app.module'),
        ),
    ]
