# Generated by Django 4.0 on 2023-09-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_module_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('config', models.JSONField(default=dict, null=True, verbose_name='测试库配置')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': '用例模块', 'verbose_name_plural': '用例模块'},
        ),
        migrations.CreateModel(
            name='EnvVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='变量名')),
                ('value', models.JSONField(default=dict, null=True, verbose_name='变量值')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.env', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': '环境变量',
                'verbose_name_plural': '环境变量',
            },
        ),
    ]
