# Generated by Django 4.0 on 2023-09-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_env_alter_module_options_envvariable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrecord',
            options={'verbose_name': '测试纪录', 'verbose_name_plural': '测试报告'},
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='log',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='details',
            field=models.JSONField(default=dict, null=True, verbose_name='步骤详情'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='last_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待运行'), (1, '全部通过'), (2, '部分失败')], default=0, null=True, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(blank=True, to='app.TestCase', verbose_name='测试用例'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待运行'), (1, '通过'), (2, '失败'), (3, '异常')], default=0, null=True, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.testcase', verbose_name='测试报告'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testreport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.testreport', verbose_name='测试报告'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='fail_num',
            field=models.PositiveIntegerField(default=0, verbose_name='失败用例数'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='pass_num',
            field=models.PositiveIntegerField(default=0, verbose_name='通过用例数'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待运行'), (1, '全部通过'), (2, '部分失败')], default=0, null=True, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='testplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.testplan', verbose_name='测试计划'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='运行总数'),
        ),
    ]
