# Generated by Django 4.0 on 2023-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_testrecord_options_remove_testrecord_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='error_msg',
            field=models.TextField(null=True, verbose_name='错误信息'),
        ),
    ]
