# Generated by Django 4.0 on 2023-09-04 11:14

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_step_options_alter_testcase_options_step_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='testcase',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_steps', to='app.testcase', verbose_name='所属用例'),
        ),
    ]
