# Generated by Django 4.0 on 2023-09-04 11:29

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_step_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_modules', to='app.module', verbose_name='上级模块'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='module',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.module', verbose_name='用例模块'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='排序'),
        ),
    ]
