# Generated by Django 4.0 on 2023-09-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_module_parent_alter_step_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': '用例模块', 'verbose_name_plural': '用例模块'},
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testreport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='app.testreport', verbose_name='测试报告'),
        ),
    ]
