# Generated by Django 4.0 on 2023-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_testrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='error_msg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='错误信息'),
        ),
    ]
