# Generated by Django 4.0 on 2023-09-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_testcase_last_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='error_num',
            field=models.PositiveIntegerField(default=0, verbose_name='出错用例数'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.testcase', verbose_name='测试用例'),
        ),
    ]
