# Generated by Django 4.0 on 2023-09-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_testreport_error_num_alter_testrecord_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='last_status',
        ),
    ]
