# Generated by Django 4.0 on 2023-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_testplan_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='chart',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='运行统计'),
        ),
    ]
