# Generated by Django 4.0 on 2023-09-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_testreport_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.env', verbose_name='测试环境'),
        ),
    ]
