# Generated by Django 4.0 on 2023-09-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_testplan_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='env',
        ),
    ]
