# Generated by Django 4.0 on 2023-09-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_env_config_libconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, null=True, verbose_name='测试库配置')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_configs', to='app.env', verbose_name='所属环境')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.library', verbose_name='操作库')),
            ],
        ),
        migrations.DeleteModel(
            name='LibConfig',
        ),
    ]
