# Generated by Django 4.0 on 2023-09-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_libraryconfig_delete_libconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryconfig',
            options={'verbose_name': '操作库配置', 'verbose_name_plural': '操作库配置'},
        ),
        migrations.AlterField(
            model_name='libraryconfig',
            name='config',
            field=models.JSONField(default=dict, help_text='操作库类初始化参数,字典格式', null=True, verbose_name='测试库配置'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryconfig',
            unique_together={('env', 'library')},
        ),
    ]
