# Generated by Django 4.0 on 2023-09-04 19:38

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_libraryconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='操作库类初始化参数,字典格式', null=True, verbose_name='测试库配置'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '用例分类',
                'verbose_name_plural': '用例分类',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='用例模块'),
        ),
    ]
