# Generated by Django 4.0 on 2023-09-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_libraryconfig_config_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
