# Generated by Django 4.0 on 2023-09-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_testcase_module_delete_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvariable',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_variables', to='app.env', verbose_name='所属环境'),
        ),
    ]
