# Generated by Django 4.0 on 2023-09-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_envvariable_env'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='order',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='用例分类'),
        ),
    ]
