# Generated by Django 4.0 on 2023-09-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_testplantestcase_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(blank=True, through='app.TestPlanTestCase', to='app.TestCase', verbose_name='测试用例'),
        ),
    ]
