# Generated by Django 4.0 on 2023-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_testcase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='retry_interval',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='失败重试间隔'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='retry_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='失败重试次数'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='超时时间'),
        ),
        migrations.AddField(
            model_name='testplantestcase',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='超时时间'),
        ),
    ]
