# Generated by Django 4.0 on 2023-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_testplantestcase_testcase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['order'], 'verbose_name': '操作方法', 'verbose_name_plural': '操作方法'},
        ),
        migrations.AddField(
            model_name='method',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='排序'),
        ),
    ]
