# Generated by Django 4.0 on 2023-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_testplan_periodic_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('testcase_error', '用例问题'), ('env_error', '环境问题'), ('data_error', '数据问题'), ('bug', '疑似Bug')], max_length=128, null=True, verbose_name='错误原因'),
        ),
    ]
