# Generated by Django 4.0 on 2023-09-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0041_testrecord_error_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='auth.user', verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('platform_error', '平台问题'), ('testcase_error', '用例问题'), ('env_error', '环境问题'), ('data_error', '数据问题'), ('bug', '疑似Bug')], max_length=128, null=True, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='auth.user', verbose_name='执行人'),
        ),
    ]
