# Generated by Django 4.0 on 2023-09-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_testrecord_create_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='error_num',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='fail_num',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='pass_num',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='total',
        ),
    ]
