# Generated by Django 4.0 on 2023-09-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_args_library_init_args_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
