# Generated by Django 4.0 on 2023-09-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_library_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='数据')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='resources', verbose_name='数据文件')),
            ],
            options={
                'verbose_name': '测试资源',
                'verbose_name_plural': '测试资源',
            },
        ),
    ]
