# Generated by Django 4.0 on 2023-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_resource_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='testcase',
        ),
        migrations.AddField(
            model_name='testcase',
            name='resources',
            field=models.ManyToManyField(blank=True, to='app.Resource', verbose_name='测试资源'),
        ),
    ]
