"""
Django settings for fasttest project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+k&j&uhu@tgq!+$2=o^0144$!yr!fvwvd%x@8h5%5m4)$pma2-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'taggit',
    # for api
    'rest_framework',
    'django_filters',
    # celery
    'django_celery_results',
    'django_celery_beat',
    # for admin
    'django_object_actions',
    'import_export',
    'admin_model_list_order',
    'django_cascading_dropdown_widget',
    'adminsortable',
    'prettyjson',
    # 'nested_admin',
    'attachments',

    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'admin_model_list_order.middleware.AdminModelListOrder',
]

ROOT_URLCONF = 'fasttest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'fasttest.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'fastapi',  # 需要手动创建库
#         'USER': 'root',
#         'PASSWORD': 'passw0rd',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

USE_L10N = False
DATETIME_FORMAT = 'Y年m月d日 H:i:s'
DATE_FORMAT = 'Y年m月d日'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEST_LIBRARIES = [
    {'Common': 'libs.commonlib'},
    {'Assert': 'libs.assertlib'},
    {'Http': 'libs.httplib'},
    {'Selenium': 'libs.seleniumlib'},
    {'Chainmaker': 'libs.chainmakerlib'},
    {'ContractManage': 'libs.chainmakerlib'},
]

CSRF_COOKIE_HTTPONLY = True

ADMIN_MODEL_DEFAULT_PRIORITY = 100


SIMPLEUI_HOME_INFO = False
SIMPLEUI_LOADING = False
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_LOGIN_PARTICLES = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'layui.css'

SIMPLEUI_LOGO = '/static/img/fast.png'

SIMPLEUI_ICON = {
    '测试管理': 'fas fa-flask',
    '测试环境': 'fab fa-envira',
    '用例分类': 'fas fa-folder',
    '测试用例': 'fas fa-vial',
    '测试计划': 'fas fa-calendar-check',
    '测试报告': 'fas fa-chart-pie',
    '测试纪录': 'fas fa-rectangle-list',
    'Celery Results': 'fas fa-list',
}

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': True,
    # 'menu_display': ['测试管理', '周期任务', '认证和授权', '管理'],

}

CELERY_BROKER_URL = 'amqp://guest:guest@localhost'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True  # 是否使用TLS安全传输协议
EMAIL_HOST = 'smtp.sina.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'test_results@sina.com'
EMAIL_HOST_PASSWORD = '4b62a57acb306ca9'


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}



LIST_PER_PAGE = 15
